name: CI/CD Docker Crucigrama App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen del Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crucigrama-frontend:latest

      - name: Construir y subir imagen del Backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crucigrama-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Ejecutar imagen del Frontend
        run: |
          docker run -d -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/crucigrama-frontend:latest
          
      - name: Ejecutar imagen del Backend
        run: |
          docker run -d -p 8081:3000 ${{ secrets.DOCKERHUB_USERNAME }}/crucigrama-backend:latest
